theme: jekyll-theme-minimal
title: "Maniu Linux Corner"
description: "Welcome to Maniu's Linux Corner"
show_downloads: false
github_username:  maniu-linux-corner

github:
      is_user_page: false
      is_project_page: false
